//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public int IdBantAccount { get; set; }
        public string BankName { get; set; }
        public int BranchNum { get; set; }
        public int AccountNum { get; set; }
        public string OwnerName { get; set; }
        public int IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
