//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksInLibrary
    {
        public int IdBookInLibrary { get; set; }
        public int IdBook { get; set; }
        public int IdLibrary { get; set; }
        public Nullable<int> LendingDuration { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Libraries Libraries { get; set; }
        public virtual StatusLending StatusLending { get; set; }
    }
}
