//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookmarkDBEntities1 : DbContext
    {
        public BookmarkDBEntities1()
            : base("name=BookmarkDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BooksInLibrary> BooksInLibrary { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Lendings> Lendings { get; set; }
        public virtual DbSet<Libraries> Libraries { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<SecrateryInLibrary> SecrateryInLibrary { get; set; }
        public virtual DbSet<StatusLending> StatusLending { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<subscribers> subscribers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
