//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int IdPayment { get; set; }
        public int Type { get; set; }
        public int IdCreditCard { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int IdUser { get; set; }
    
        public virtual CreditCards CreditCards { get; set; }
        public virtual Users Users { get; set; }
    }
}
