//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecrateryInLibrary
    {
        public int IdSecretaryInLibrary { get; set; }
        public int IdSecretary { get; set; }
        public int IdLibrary { get; set; }
    
        public virtual Libraries Libraries { get; set; }
        public virtual Users Users { get; set; }
    }
}
